### ISSUE TITLE
Not works with Meteor 1.3.x

### ISSUE THREAD

**Issue by g41n** [MasterAM/meteor-ol3#6]
Hello to all, If I provide a custom mapSource on local images like this:

```
$scope.mapSource = new ol.source.OSM();
//$scope.mapSource.setUrl("https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png#aaa");
$scope.mapSource.setUrl("map/{a-c}.{z}.{x}.{y}.png");
$scope.map = new ol.Map({
    layers: [
        new ol.layer.Tile({
            preload: 4,
            source: $scope.mapSource
        })
    ],
...
```

where map is a dir under public, I have the 403 forbidden error:

```
Failed to load resource: the server responded with a status of 403 (Forbidden)    http://localhost:12136/map/c.6.35.23.png
```

Kinda strange... with version 1.2.x the link was `http://meteor.local/map/c.6.35.23.png` and worked like a charm...

Please, help.

**Comment by MasterAM** [comment]
Strange indeed.

Meteor 1.3 came with a new local server on Cordova, which made hot code push more efficient.
The new server would be my first guess. If you have a minimal reproduction of the issue, I can take a look.

Which platform did you use? Is it working on the desktop?

BTW, in Meteor v1.3, you can install OpenLayers directly from npm (that's the reason I am hardly updating it anymore).

**Comment by g41n** [comment]
I've created a repo for the reproduction here https://github.com/g41n/openlayers-meteor13-test

Thanks for the support :)

**Comment by MasterAM** [comment]
I also got the same results with your repo on an iPhone, but did not have time to make an Android build. The map worked just fine when using a web browser, which lead me to believe that the issue is not related to the ol3 package.

I suspect one of the two:
1. You mobile config file may be wrong (although the access rules seem fine at first glance).
2. Some bug in the [mobile web server](https://github.com/meteor/cordova-plugin-meteor-webapp).
